# Generated by Django 3.1.4 on 2020-12-03 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('latitude', models.IntegerField()),
                ('longitude', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('date', models.DateTimeField()),
                ('cashprize', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.city')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_finished', models.BooleanField(default=False)),
                ('black_pawns_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='played_as_black', to=settings.AUTH_USER_MODEL)),
                ('referees', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournament')),
                ('white_pawns_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='played_as_white', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
